### PR TITLE
refactor(generator): Welcome App is now provisioned from Docker image

### PR DESCRIPTION
**Pull request by quintesse**
DO NOT MERGE YET!

### CODE REVIEW

**Comment by quintesse** [comment]
> LGTM

Well actually, this is what I wrote on Slack:

> I hacked it together quickly so it doesn't actually work yet
> But it should be 99% there. It starts, it gets the correct image, there are no errors... but then there's a message the app is not ready
> But you should at least be able to take a look and fix it (or tell me how to fix it), I need to continue with some other stuff first
> 
> Possibly something to do with the nginx configuration? Whenever I go to the welcome app route it immediately seems to redirect to port 8080 (which for OpenShift isn't correct of course)
> Yup, when I go to the route I receive a 301 from the server redirecting me to the same route + :8080
> 
> No idea why it does that. Comparing with the Frontend nginx.conf I don't see many differences. The only major difference seems to be that the Frontend uses a public nginx image instead of a RH one
> Ok, if I go explicitly to `/index.html` it works
> This might help: https://serverfault.com/questions/351212/nginx-redirects-to-port-8080-when-accessing-url-without-slash
> When going to the index page I get the error "`INJECTED_APP_CONFIG` is not defined"

So I was hoping either you @gastaldi or @ia3andy would be able to take look at this and make it actually work :-)

**Comment by gastaldi** [comment]
The script error is because the `sed` in the `endpoint.sh` script needs to be fixed

**Comment by quintesse** [comment]
Ok! 👍 That only leaves the redirect issue.

**Comment by gastaldi** [comment]
@quintesse redirect issue fixed. Leaving the fun with `sed` to @ia3andy :wink:

**Comment by gastaldi** [comment]
@quintesse all should be good now. Mind trying again?

**Pull request merged**
