### PR TITLE
fix: angular output dir append project name

### PR DESCRIPTION
**Pull request by edewit**
fixes: #126

### CODE REVIEW

**Comment by quintesse** [comment]
@edewit can you check if it also works when downloading the zip and deploying with the gap command?

**Comment by edewit** [comment]
@quintesse tested with "standalone creator" deploy using `gap`, "download" with the frontend and `gap` to install and "deploy on openshift" with the frontend. All of these scenarios work

**Comment by edewit** [comment]
screenshot from 2018-12-17 11-35-15

**Comment by quintesse** [comment]
Great thanks @edewit!

**Pull request merged**
