### PR TITLE
feat(deploy): Introduced the concept of 'tiers'

### PR DESCRIPTION
**Pull request by quintesse**
In the context of the Creator an "Application" is considered to be
a single code base (a Git repository for example). An application
could have a set of capabilities describing its features. And a set
of capabilities are supposed to only have a single "runtime". This
meant that a single application could only support a single runtime.
This was considered too limiting for the MVP so we needed to come
up with a way to support multiple runtimes in a single application.
The solution was to introduce the concept of "tiers". A tier is a
set of capabilities. A tier can only have a single runtime. But an
application can have multiple tiers. A tier also maps to a sub folder
in the code base, so each tier can have its own set of files.

### CODE REVIEW

**Comment by quintesse** [comment]
@ia3andy for the Welcome App something changes as well. Where before we had:

```
{
  application: fubar,
  shared: { }.
  extra: { },
  capabilities: [{
    all_the_stuff: "here"
  }]
}
```

we now have a new container:

```
{
  application: "fubar",
  tiers: [{
    tier: "frontend",
    shared: { }.
    extra: { },
    capabilities: [{
      all_the_stuff: "here"
    }]
  }]
}
```

It looks more complicated than it is. You just need to loop over all the tiers to find all the capabilities. That's basically it.

**Comment by quintesse** [comment]
@ia3andy I just realized, there's another change that would be necessary: _if_ the object in the `tiers` array has a `tier` property (like "frontend" above) then the WA needs to prepend that value to all source links (you can basically think of tiers as sub folders in the root of the project). If the object does _not_ have a `tier` property it means there is no sub folder so the source links stay the way they are now.

So if you have a source link like `src/main/java/foo/bar/Baz.java` and a github URL like `github.com/john/doe` then now you create a link like `github.com/john/doe/blob/master/src/main/java/foo/bar/Baz.java`. That still stays the same if there's no `tier` property. But if there is and it's value for example is "frontend", then the link must become: `github.com/john/doe/blob/master/frontend/src/main/java/foo/bar/Baz.java`.

I hope that's clear!

**Comment by ia3andy** [comment]
@quintesse cristal clear ;)

Just a question, I know it's easier to handle it in the WA, but shouldn't it be done in when creating the WA Config. I am asking because changing this afterward in the WA may be really tricky (to sync).

**Comment by quintesse** [comment]
> Just a question, I know it's easier to handle it in the WA

No actually I hadn't even thought about handling it in the creator backend. You're right of course, best to do it there. So just forget about that last message, the backend will take care of that. Thanks!

**Comment by quintesse** [comment]
So @edewit , I decided that it would just be better to have the frontend send the same format to request a zip or a launch as what the crreator uses itself internally. Trying to "simplify" it for the Frotnend is actually making things more complex.

So this is an example of what a simple backend-only (a single unnamed tier) request would look like:

```yaml
    {
      "application": "fubar",
      "tiers": [
        {
          "shared": {
            "runtime": {
              "name": "vertx"
            },
            "maven": {
              "groupId": "org.openshift.appgen",
              "artifactId": "my-app",
              "version": "1.0.0"
            }
          },
          "capabilities": [
            {
              "module": "welcome",
            },
            {
              "module": "database",
              "props": {
                "databaseType": "postgresql"
              },
            },
            {
              "module": "rest",
            }
          ]
        }
      ]
    }
```

There are two important changes:

 - Almost all the elements that were part of the toplevel object (except for `application`)  are now inside the `tier` array.
 - The capability properties are now separate in a `props` element, instead of mixed in with `module`

The tier array itself in its simplest form as shown above just has a single element and inside that element the properties `shared` and `capabilities` (no `tier` name should exists).

Now for the case where we have both a frontend and a backend:

**Comment by quintesse** [comment]
For the case where we have both frontend and backend capabilities we simply put each of them in their own (named!) `tier`:

```yaml
    {
      "application": "fubar",
      "tiers": [
        {
          "tier": "backend",
          "shared": {
            "runtime": {
              "name": "vertx"
            },
            "maven": {
              "groupId": "org.openshift.appgen",
              "artifactId": "my-app",
              "version": "1.0.0"
            }
          },
          "capabilities": [
            {
              "module": "database",
              "props": {
                "databaseType": "postgresql"
              }
            },
            {
              "module": "rest",
            }
          ],
        },
        {
          "tier": "frontend",
          "shared": {
            "framework": {
              "name": "react"
            }
          },
          "capabilities": [
            {
              "module": "web-app",
            }
          ],
        },
        {
          "tier": "support",
          "shared": {},
          "capabilities": [
            {
              "module": "welcome",
            }
          ],
        },
      ]
    }
```

As you can see the first part looks exactly the same as the .json in the previous message. The important difference is that this time the `tiers` array element actually has a name. It has a `tier` element with the value `"backend"`. This name means that the code for that "tier" will be put in a separate sub folder within the generated project named "backend".

But in this case we have more elements in the `tiers` array. The next element has a `tier` of `"frontend"`, it's the one that contains the frontend capabilities.

And finally we have a third element with a `tier` of `"support"` (yes, you can simply use the capability's `metadata.category` for these values) that only contains the Welcome App capability.

**Comment by quintesse** [comment]
Now to make things simpler to implement you could just always create all 3 tiers while the user is navigating through the wizard pages. You could literally just start out with:

```yaml
    {
      "application": "fubar",
      "tiers": [
        {
          "tier": "support",
          "shared": {},
          "capabilities": [
          ],
        },
        {
          "tier": "backend",
          "shared": {
          },
          "capabilities": [
          ],
        },
        {
          "tier": "frontend",
          "shared": {
          },
          "capabilities": [
          ],
        }
      ]
    }
```

And fill in the `capabilities` and `shared` values while they are making their choices.

And then at the end you could do the following simple check:

 - Do all three "tiers" have at least one capability?

If not do the following:

 - Remove the tier that has no capabilities
 - Remove the "support" tier
 - Move the capability from the "support" tier to the capabilities of the remaining tier
 - Remove the `tier` property

Might sound complex but they're really very easy steps.

**Comment by ia3andy** [comment]
@quintesse This format seems good to me

**Comment by quintesse** [comment]
Btw, what the Frontend needs to send to the Backend is the following for the `/launch` endpoint:

```json
{
   "project": { all the stuff explained above },
   "clusterId": "cluster",
   "projectName": "fubar",
   "gitRepository": "repo",
   "gitOrganization": "edewit"
}
```

and for the `/zip` endpoint simply:

```json
{
   "project": { all the stuff explained above },
}
```

**Comment by quintesse** [comment]
@edewit perhaps it is simpler to see it like this:

You start with an empty `tiers. []`, like this:

```json
    {
      "application": "fubar",
      "tiers": []
    }
```

Then if the user selects something for the frontend you add a:

```json
      {
       "tier": "frontend",
        "capabilities": [
          {
            "module": "web-app"
          },
        ]
      }
```

to the array. The same for the backend, only if the user selects something you add :

```json
      {
       "tier": "backend",
        "capabilities": [
          {
            "module": "rest"
          },
        ]
      }
```

And at the end you look if you have 1 or 2 entries in the array.

If you have 1 you add 

```json
          {
            "module": "welcome"
          },
```

to the capabilities of the only tier that is in the array and you remove its `tier` attribute.

If you have 2 you add an extra support tier:

```json
      {
        "capabilities": [
          {
            "module": "welcome"
          }
        ]
      },
```

**Pull request merged**
