### PR TITLE
feat: add debug script

### PR DESCRIPTION
**Pull request by edewit**
use your favorite IDE and connect to port 9229
or type `chrome://inspect/` in chrome to debug

### CODE REVIEW

**Comment by quintesse** [comment]
Thanks @edewit !

But I have a question: could you perhaps explain a bit more how to use this?

I tried it using `chrome://inspect/` (which is awesome, I didn't know that existed) but it doesn't let me browse any sources it seems so I can't set any breakpoints?

And using my "favorite IDE" (IDEA) I have no idea how to debug a JS/TS application. The only option that seems logical "JavaScript Debug" requires me to fill in a URL. So how would I debug something that's not related to any URL?

**Comment by quintesse** [comment]
Thanks to @gastaldi for explaining you need `Attach to Node.js/Chrome` not `JavaScript Debug`

**Comment by edewit** [comment]
To open files in the chrome type `ctrl-p` then type the name of the file or browse in the file browser on the left.

I don't have IDEA so don't know how to do it there but you need to debug using socket 9229

**Comment by quintesse** [comment]
@edewit I tried to open a file using Chrome but it doesn't show any of the files from the project, just the `bin.js` where it starts and a whole bunch of `internal/..` files.

**Pull request merged**
