### PR TITLE
WIP Adding support for EAP.

### PR DESCRIPTION
**Pull request by ehsavoie**
Currently nothing distinguish JBoss EAP from WildFly.
Only through version can we support EAP vs WildFly

### CODE REVIEW

**Comment by quintesse** [comment]
@ehsavoie thanks for the PR! Btw, when you say "Currently nothing distinguish JBoss EAP from WildFly." does that literally mean _nothing_ (besides the name)?

**Comment by quintesse** [comment]
What we really want is just a single set of generators for both Wildfly and EAP, with simple a simple test for determining which has been selected by the user and based on that deciding to use one builder image or another and adding some different ENV vars.

We could do that now by adding a simple function, eg. `isEAP()`, that returns `true` for EAP and `false` for Wildfly. We could hard-code it to return `false` for now but that would at least mean that when the Version stuff gets implemented it would be very simple to make this work and the code would already be in the required format.

But if you want to wait for the Version features to be implemented that's okay too :-)

**Comment by ehsavoie** [comment]
Reusing wildfly generators. Currently all is managed buy a isEAP() function that always returns false. Having it return true brings EAP is.

**Comment by quintesse** [comment]
This would have to be redone for the JVM-version of the Creator. Sorry. Closing.

**Pull request closed without merging**
