### PR TITLE
feat(go): Add support for Go language

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by quintesse** [comment]
👍

**Comment by sbose78** [comment]
Cool, let me check out this branch and give these a try.

**Comment by sbose78** [comment]
Is a `./gap deploy` supposed to work?

**Comment by gastaldi** [comment]
@sbose78 the `gap` is not yet being copied over to the repository, I'll fix that in the next commit

**Comment by gastaldi** [comment]
@sbose78 `./gap deploy` and `./gap push` now works, please give it a  try

**Comment by quintesse** [comment]
Not sure if I forgot to add my comments or they got lost when now code got pushed. Anyway I'll repeat myself just to be sure:

It seems that the `gap` script used in this PR is a copy from the Node.js one, it's better to base the `gap` script on the ones used by the Java-based platforms. It's has a bit more options. (like dealing with pushing source vs binaries)

**Comment by gastaldi** [comment]
For reference purposes, `lib/core/resources/templates/centos_go-toolset-7-centos7.json` is generated using the `yarn generate` command

**Comment by quintesse** [comment]
This would have to be redone for the JVM-version of the Creator. Sorry. Closing.

**Pull request closed without merging**
